name: eid sigin

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  ssh-connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          HOST: 0.tcp.jp.ngrok.io
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$HOST" >> ~/.ssh/known_hosts

      - name: SSH to flion@208-6(ngrok)
        env:
          USER: flion202304@gmail.com
          HOST: 0.tcp.jp.ngrok.io
          PORT: 11176          
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ./id_rsa -p "$PORT" "$USER@$HOST" "ansible-playbook ansible-playbook/eid-signin.yaml"
